### DISCUSSION TITLE
x-collapse does not hide collapsed content from the accessibility tree

### DISCUSSION THREAD

**Discussion by philwolstenholme** [alpinejs/alpine#2277] [7. Bugs (archived)] [answered]
Hi,

Big fan of Alpine! Thanks for all the time that has been put into it :) 

I was checking out [x-collapse](https://alpinejs.dev/plugins/collapse) and noticed that visually collapsed content is not hidden/removed from the accessibility tree, so keyboard users can tab to focusable elements that should be hidden, and the content may be announced to screenreader users.

At the moment we just hide content with `overflow: hidden; height: 0px;` but this isn't enough to hide content from assistive tech.

One way to hide the content safely would be to add a `hidden` attribute after the transition has ended and the content has been collapsed (or add it on load), and remove the attribute before un-collapsing the content.

The `hidden` attribute approach is particularly nice as it will play nicely with Tailwind's https://tailwindcss.com/docs/space utility. The utility won't add space around content that has been hidden with `hidden`:

```css
.space-y-1>:not([hidden])~:not([hidden]) {
    --tw-space-y-reverse: 0;
    margin-top: calc(.25rem * calc(1 - var(--tw-space-y-reverse)));
    margin-bottom: calc(.25rem * var(--tw-space-y-reverse))
}
```

You could also add `display:none;` as an inline style alternative, but it wouldn't play nicely with Tailwind's space utilities.
