### DISCUSSION TITLE
Transitionend event listener doesn't work on Safari (macOS + iOS)

### DISCUSSION THREAD

**Discussion by kslstn** [alpinejs/alpine#2810] [7. Bugs (archived)]
Safari ignores the expression for `x-on:transitionend` when used like this:
```html
<p
  x-show="show"
  x-cloak
  x-transition:enter="transition"
  x-transition:enter-start="opacity-0"
  x-transition:enter-end="opactity-1"
  x-transition:leave="transition"		 
  x-transition:leave-start="opacity-1"
  x-transition:leave-end="opacity-0"
  x-on:transitionend="transitionCount++"
></p>
```
```css
.transition{
  transition: all linear 200ms;
}
.opacity-0{
  opacity: 0;
}
.opacity-1{
  opacity: 1;
}
```
See [this Codepen for a demo](https://codepen.io/kslstn/pen/KKZQxRM).

Firefox and Chrome do detect the event. Safari does react to `ontransitionend` in [this plain JS example](https://codepen.io/kslstn/pen/wvpyOpX). And it also reacts to `x-on:transitionstart`.
